# Alacritty Configuration (TOML)
[window]
opacity = 0.92
decorations = "None"

[window.padding]
x = 0
y = 1

[font]
size = 14.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.offset]
x = 0
y = -1

[font.glyph_offset]
x = 0
y = 0


[colors.primary]
background = "#16161D"
foreground = "#d5c6e0"
dim_foreground = "#686858"
bright_foreground = "#eaf3f5"

[colors.cursor]
text = "#16161D"
cursor = "#d5c6e0"

[colors.vi_mode_cursor]
text = "#16161D"
cursor = "#984695"

[colors.search.matches]
foreground = "#16161D"
background = "#984695"

[colors.search.focused_match]
foreground = "#16161D"
background = "#9ef01a"

[colors.footer_bar]
foreground = "#16161D"
background = "#75797a"

[colors.hints.start]
foreground = "#16161D"
background = "#fcc25d"

[colors.hints.end]
foreground = "#16161D"
background = "#75797a"

[colors.selection]
text = "#16161D"
background = "#703871"

[colors.normal]
black = "#403d39"
red = "#fb3475"
green = "#7cb375"
yellow = "#fcc25d"
blue = "#b194fa"
magenta = "#c51af9"
cyan = "#d694fa"
white = "#d5c6e0"

[colors.bright]
black = "#686858"
red = "#fc735d"
green = "#9ef01a"
yellow = "#fcc25d"
blue = "#b194fa"
magenta = "#d694fa"
cyan = "#7cb375"
white = "#eaf3f5"

[[colors.indexed_colors]]
index = 16
color = "#fc735d"

[[colors.indexed_colors]]
index = 17
color = "#984695"
